Modified and added new parameters!
uparma/uparma-lib pull request #150
Opened 2023-08-14 19:42 UTC by YoungKrug

Parameters from Msfragger that were not originally added to the Uparam are included. Please let me know if anything is missing!

2023-08-18 16:59 UTC, StSchulze requested changes
Good start!
I left comments as a to-do list as we discussed.
In addition, there were a couple of parameters that are wrong in the current uparma version (precursor_max_mass and precursor_min_mass from what I remember). Those should be updated/taken out.

2023-08-21 18:43 UTC, YoungKrug commented
I have made the appropriate changes, let me know if I missed anything!

2023-08-21 21:28 UTC, StSchulze approved these changes

2023-08-29 09:43 UTC, tristan-ranff approved these changes

2023-08-29 09:44 UTC, merged